apiVersion: v2
name: did-web-server
description: A Helm chart to deploy the did-web-server project. 
home: "https://github.com/identinet/did-web-server"
type: application

# This is the chart version. This version number should be incremented each time you make changes
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: "0.4.1"

maintainers:
  - email: jason.syrotuck@nttdata.com
    name: Jsyro
    url: https://github.com/Jsyro